Heroku/Trello/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root to: 'home#show'

  resources :cards do
    resources :todos, only: [:create]
  end

  resources :todos, only: [:destroy]
  # resources :todos, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Heroku/Trello/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Heroku/Trello/app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  has_many :todo, dependent: :destroy
  validates :title, presence: true

  # scope :actual, -> { where(created_at: Date.today - 1.month) }
  scope :actual, -> {}
end

Heroku/Trello/app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
  belongs_to :card
  validates :title, presence: true
  validates :description, presence: true
end

Heroku/Trello/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token
end

Heroku/Trello/app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  before_action :set_card, only: %i[show edit update destroy]

  layout 'cards'
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.actual
  end

  # GET /cards/1
  # GET /cards/1.json
  def show; end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit; end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = set_card
    byebug
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_card
    @card = Card.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def card_params
    params.require(:card).permit(:title)
  end
end

Heroku/Trello/app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = TrelloSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

Heroku/Trello/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # layout 'cards'

  def show; end
end

Heroku/Trello/app/controllers/todos_controller.rb
# frozen_string_literal: true

class TodosController < ApplicationController
  def create
    @card = Card.find(params[:card_id])
    @todo = @card.todo.build(title: params[:title], description: params[:description])
    if @todo.save
      flash[:notice] = 'ToDo was successfully created'
    else
      flash[:alert] = @todo.errors.full_messages.join(', ')
    end
    redirect_to card_url(id: @card)
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to card_url(id: @todo.card)
  end
end

Heroku/Trello/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

Heroku/Trello/app/helpers/cards_helper.rb
# frozen_string_literal: true

module CardsHelper
end

Heroku/Trello/app/helpers/todos_helper.rb
# frozen_string_literal: true

module TodosHelper
end

Heroku/Trello/app/views/application/_trello_header.html.slim
header.header
    .logo
    = link_to cards_path
        img.logo src=image_url('trello-logo-blue.png') alt=""/
    nav.menu
        => link_to 'Home', root_path, class: 'header__link'
        => link_to 'Cards', cards_path, class: 'header__link'

Heroku/Trello/app/views/cards/_form.html.slim
= form_with(model: card, local: true) do |form|
  - if card.errors.any?
    #error-explanation
      h2
        = pluralize(card.errors.count, "error")
        |  prohibited this card from being saved:
      ul
        - card.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .actions
    = form.submit

Heroku/Trello/app/views/cards/edit.html.slim
h1
  | Editing Card
= render 'form', card: @card
= link_to 'Show', @card
|  |
= link_to 'Back', cards_path

Heroku/Trello/app/views/cards/index.html.slim
.cards.js-cards
  p#notice
    = notice
  h1
    ' Cards
    span.sorter.js-sort-asc Sort by title
    span.sorted.js-sort-desc.hidden Reverse sort by title

  button.btn.btn-light type="button"
    = link_to 'New Card', new_card_path

  ul.cards-list.js-cards-list
    - @cards.each do |card|
      li.cards-list__item.js-item data-card=card.to_json
        .cards-list__header
          = link_to card.title, card
        .cards-list__icons
          = link_to edit_card_path(card), class: 'cards-list__icon' do
            = image_tag 'edit.svg'
          = link_to card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'cards-list__icon' do
            = image_tag 'delete.svg'
  br

= image_tag 'work.jpg', class: 'mem'

Heroku/Trello/app/views/cards/new.html.slim
h1
  | New Card
= render 'form', card: @card
= link_to 'Back', cards_path

Heroku/Trello/app/views/cards/show.html.slim
p#notice
  = notice
p#alert[style="color: red"]
  = alert
p.title
  strong
    ' Title:
  = @card.title
= render "todos/form", card: @card, todo: @card.todo.build

p
  strong
    ' Todos:
  ol.todos
    - @card.todo.each do |todo|
      - if !todo.id.nil?
        li

          b
            =	todo.title
          ' :
          =	todo.description
          = link_to todo_path(id: todo.id), method: :delete, data: { confirm: "Are you sure?" }, class: 'todos__icon' do
            = image_tag 'delete.svg'
        end
    end
= link_to 'Edit', edit_card_path(@card)
|  |
= link_to 'Back', cards_path

Heroku/Trello/app/views/home/show.html.slim
p.home
    |Well...... Welcome, I guess
    br/
    |Projects:

nav.menu
    => link_to 'Cards', cards_path, class: 'header__link'

Heroku/Trello/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Trello
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

Heroku/Trello/app/views/layouts/cards.html.slim
doctype html
html
  head
    title
      | Trello
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'trello_header'
    = yield

Heroku/Trello/app/views/todos/_form.html.erb
<%= form_with(url: card_todos_url(card_id: card.id), 
method: :post) do |form| %>

<% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Heroku/Trello/app/views/todos/_form.html.slim
= form_with(url: card_todos_url(card_id: card.id),  method: :post) do |form|
- if todo.errors.any?
  #error-explanation
    h2
      = pluralize(todo.errors.count, "error")
      |  prohibited this todo from being saved:
    ul
      - todo.errors.full_messages.each do |message|
        li
          = message
  .field
    = form.label :title
    = form.text_field :title
    = form.label :description
    = form.text_field :description
  .actions
    = form.submit